vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<leader>w", vim.cmd.write)
vim.keymap.set("n", "<leader>wa", vim.cmd.wall)
vim.keymap.set("n", "<leader>wq", function()
    vim.cmd.write()
    vim.cmd.quit()
end)
vim.keymap.set("i", "jj", "<Esc>") 
vim.keymap.set("n", "<leader>sv", "<C-w>v")
vim.keymap.set("n", "<leader>sh", "<C-w>s")
vim.keymap.set("n", "<leader>q", vim.cmd.quit)
vim.keymap.set("n", "<leader>qq", "%bd | e # | normal `\"")
vim.keymap.set("n", "<leader>r", ":%s/\\<<C-r><C-w>\\>/")
vim.keymap.set("n", "<leader>tn", "<C-w><C-w>")
